# Generated by Django 3.1.7 on 2021-04-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0004_auto_20210322_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
