# Generated by Django 3.1.7 on 2021-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0005_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField(default=-1)),
                ('link', models.CharField(max_length=500, unique=True)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
