# Generated by Django 3.1.7 on 2021-04-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0006_gpumodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPUModel2',
        ),
    ]
