# Generated by Django 3.1.7 on 2021-04-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0008_gpumodel_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpumodel',
            name='prices',
        ),
    ]
