# Generated by Django 3.1.7 on 2021-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0009_remove_gpumodel_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpumodel',
            name='last_prices',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
