# Generated by Django 3.1.7 on 2021-04-14 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0011_remove_gpumodel_last_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=-1)),
                ('date', models.DateTimeField(default=datetime.date)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpu.gpumodel')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
