# Generated by Django 3.1.7 on 2021-04-21 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0021_auto_20210419_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 19, 8, 9, 252363)),
        ),
    ]
