# Generated by Django 3.1.7 on 2021-04-21 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0023_auto_20210420_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fake',
            new_name='Notification',
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 19, 27, 9, 820095)),
        ),
    ]
