# Generated by Django 3.1.7 on 2021-04-21 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0024_auto_20210420_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
        migrations.AddField(
            model_name='notification',
            name='gpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpu.gpumodel'),
        ),
        migrations.AddField(
            model_name='notification',
            name='model_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 19, 30, 41, 834668)),
        ),
    ]
