# Generated by Django 3.1.7 on 2021-04-21 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0028_auto_20210420_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 14, 7, 41, 818829, tzinfo=utc)),
        ),
    ]
