# Generated by Django 3.1.7 on 2021-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0030_auto_20210421_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='decrease',
            field=models.BooleanField(default=False),
        ),
    ]
