# Generated by Django 3.1.7 on 2021-04-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0032_auto_20210427_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'ordering': ['date']},
        ),
    ]
