# Generated by Django 3.1.7 on 2021-04-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0034_auto_20210427_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['user']},
        ),
    ]
