# Generated by Django 3.1.7 on 2021-04-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0035_auto_20210427_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'ordering': ['-date']},
        ),
    ]
